In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.feature_selection import variance_threshold
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,r2_score,classification_report,mean_squared_error,confusion_matrix
from sklearn.ensemble import RandomForestClassifier

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
data=pd.read_csv('santander-train.csv')
data.head(4)

ID  var3  var15  imp_ent_var16_ult1  imp_op_var39_comer_ult1  \
0   1     2     23                 0.0                      0.0   
1   3     2     34                 0.0                      0.0   
2   4     2     23                 0.0                      0.0   
3   8     2     37                 0.0                    195.0   

   imp_op_var39_comer_ult3  imp_op_var40_comer_ult1  imp_op_var40_comer_ult3  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                    195.0                      0.0                      0.0   

   imp_op_var40_efect_ult1  imp_op_var40_efect_ult3  ...  \
0                      0.0                      0.0  ...   
1                      0.0                      0.0  ...   
2                      0.0                      0.0  ...   
3                      0.0                      0.0  ...   

   saldo_medio_var33_hace2  saldo_medio_var33_hace3  saldo_medio_var33_ult1  \
0                      0.0                      0.0                     0.0   
1                      0.0                      0.0                     0.0   
2                      0.0                      0.0                     0.0   
3                      0.0                      0.0                     0.0   

   saldo_medio_var33_ult3  saldo_medio_var44_hace2  saldo_medio_var44_hace3  \
0                     0.0                      0.0                      0.0   
1                     0.0                      0.0                      0.0   
2                     0.0                      0.0                      0.0   
3                     0.0                      0.0                      0.0   

   saldo_medio_var44_ult1  saldo_medio_var44_ult3     var38  TARGET  
0                     0.0                     0.0  39205.17       0  
1                     0.0                     0.0  49278.03       0  
2                     0.0                     0.0  67333.77       0  
3                     0.0                     0.0  64007.97       0  

[4 rows x 371 columns]

In [5]:
x=data.drop('TARGET', axis=True)
y=data['TARGET']
x.shape,y.shape

((76020, 370), (76020,))

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0,stratify=y)

### Removing features with low variance

VarianceThreshold is a simple baseline approach to feature selection. It removes all features whose variance doesn’t meet some threshold. By default, it removes all zero-variance features, i.e. features that have the same value in all samples.


STEP 1
Constant Feature Removal by VarianceThreshold

In [12]:
from sklearn.feature_selection import VarianceThreshold
constant_feature=VarianceThreshold(threshold=0)
constant_feature.fit(x_train)

VarianceThreshold(threshold=0)

In [13]:
constant_feature.get_support().sum()

334

In [20]:
constant_list=[not i for i in constant_feature.get_support()]
x.columns[constant_list]

Index(['ind_var2_0', 'ind_var2', 'ind_var27_0', 'ind_var28_0', 'ind_var28',
       'ind_var27', 'ind_var41', 'ind_var46_0', 'ind_var46', 'num_var27_0',
       'num_var28_0', 'num_var28', 'num_var27', 'num_var41', 'num_var46_0',
       'num_var46', 'saldo_var28', 'saldo_var27', 'saldo_var41', 'saldo_var46',
       'imp_amort_var18_hace3', 'imp_amort_var34_hace3',
       'imp_reemb_var13_hace3', 'imp_reemb_var17_hace3',
       'imp_reemb_var33_hace3', 'imp_trasp_var17_out_hace3',
       'imp_trasp_var33_out_hace3', 'num_var2_0_ult1', 'num_var2_ult1',
       'num_reemb_var13_hace3', 'num_reemb_var17_hace3',
       'num_reemb_var33_hace3', 'num_trasp_var17_out_hace3',
       'num_trasp_var33_out_hace3', 'saldo_var2_ult1',
       'saldo_medio_var13_medio_hace3'],
      dtype='object')

In [21]:
x_train_filter=constant_feature.transform(x_train)
x_test_filter=constant_feature.transform(x_test)

In [23]:
x_test_filter.shape,x_train.shape

((15204, 334), (60816, 370))

## Quassi Constant Removal

In [25]:
quassi_filter=VarianceThreshold(threshold=0.01)
quassi_filter.fit(x_train_filter) # x_train_filter is filter object after performing constant removal


VarianceThreshold(threshold=0.01)

In [27]:
x_train_quassi_filter=quassi_filter.transform(x_train_filter)
x_test_quassi_filter=quassi_filter.transform(x_test_filter)

In [29]:
x_train_quassi_filter.shape,x_train_filter.shape,x_train.shape

((60816, 274), (60816, 334), (60816, 370))

In [ ]:
Main Dataset

In [33]:
from sklearn import metrics
random_model = RandomForestClassifier(n_estimators = 100, random_state=0)
random_model.fit(x_train, y_train)
y_pred = random_model.predict(x_test)
print("Accuracy is", metrics.accuracy_score(y_test, y_pred)*100)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix is :", cm, sep='\n')

Accuracy is 95.75769534333071
Confusion Matrix is :
[[14548    54]
 [  591    11]]


After Removing Constant

In [34]:
random_model = RandomForestClassifier(n_estimators = 100, random_state=0)
random_model.fit(x_train_filter, y_train)
y_pred2 = random_model.predict(x_test_filter)
print("Accuracy is", metrics.accuracy_score(y_test, y_pred2)*100)
cm = confusion_matrix(y_test, y_pred2)
print("Confusion Matrix is :", cm, sep='\n')

Accuracy is 95.81689029202842
Confusion Matrix is :
[[14555    47]
 [  589    13]]


After Quassi Constant Removal

In [36]:
random_model = RandomForestClassifier(n_estimators = 100, random_state=0)
random_model.fit(x_train_quassi_filter, y_train)
y_pred3 = random_model.predict(x_test_quassi_filter)
print("Accuracy is", metrics.accuracy_score(y_test, y_pred3)*100)
cm = confusion_matrix(y_test, y_pred3)
print("Confusion Matrix is :", cm, sep='\n')

Accuracy is 95.77742699289661
Confusion Matrix is :
[[14547    55]
 [  587    15]]


Duplicate Feature Removal - feature has exact same values 
this duplicate feature do not add any value to our model

for duplicate feature removal we dont have any pakage to perform but we have row vise find duplicate is alvailable thats why we need to tranpose dataset

In [56]:
x_test_t=x_test_quassi_filter.T
x_train_t=x_train_quassi_filter.T

In [57]:
type(x_train_t)

numpy.ndarray

In [58]:
x_train_t=pd.DataFrame(x_train_t)
x_test_t=pd.DataFrame(x_test_t)

In [59]:
type(x_train_t)

pandas.core.frame.DataFrame

In [60]:
x_train_t.duplicated().sum()

17

In [62]:
duplicated=x_train_t.duplicated()
keep_feature=[not i for i in duplicated ]
x_train_f=x_train_t[keep_feature].T
x_test_f=x_test_t[keep_feature].T

In [52]:
#x_train_t=x_train_t.drop_duplicates(inplace=True)
#x_test_t=x_test_t.drop_duplicates(inplace=True)


In [63]:
random_model = RandomForestClassifier(n_estimators = 100, random_state=0)
random_model.fit(x_train_f, y_train)
y_pred5 = random_model.predict(x_test_f)
print("Accuracy is", metrics.accuracy_score(y_test, y_pred5)*100)
cm = confusion_matrix(y_test, y_pred5)
print("Confusion Matrix is :", cm, sep='\n')

Accuracy is 95.77742699289661
Confusion Matrix is :
[[14547    55]
 [  587    15]]
