In [4]:
print('hello world')

hello world


In [5]:
hw='Hello World'
hw

'Hello World'

In [6]:
import tensorflow as tf

In [7]:
hello=tf.constant("Hello World")

In [8]:
sess=tf.Session()

In [9]:
sess.run(hello)

b'Hello World'

In [10]:
sess.close()

##  Variables - Constant -Placeholder

In [16]:
const1=tf.constant(10)

In [17]:
const1

<tf.Tensor 'Const_1:0' shape=() dtype=int32>

In [18]:
var1=tf.Variable(100)

In [19]:
var1

<tf.Variable 'Variable_1:0' shape=() dtype=int32_ref>

In [20]:
# tensorfloww offers mathematical method like add
# there is also operator overlading so yo can also use zero+one
sum1=tf.add(const1,var1)

In [21]:
product = tf.multiply(var1,sum1)

In [22]:
#const2=tf.assign(const1,var1)

In [23]:
#you need this when using Variable only
#if you are using constant and placeholder - you do not need this line of code

In [41]:
init_op=tf.global_variables_initializer()

In [42]:
sess=tf.Session()


In [43]:
sess.run(const1)

10

In [44]:
#sess.run(var1)

In [45]:
sess.run(init_op)

In [46]:
print(sess.run(var1))

100


In [47]:
#Placeholder

In [48]:
#not initialized to any value - unlike constast and variables
a=tf.placeholder(tf.float32)

In [49]:
#you connot create a variable this way
#z=tf.Variable(10.0)
#z=tf.constant(tf.float32)

In [50]:
b=a*2

In [51]:
#sess.run(b)

In [52]:
sess.run(b,feed_dict={a:3.0})

6.0

In [53]:
sess.run(b,feed_dict={a:[1,2,3,4]})

array([2., 4., 6., 8.], dtype=float32)

In [54]:
dictionary={a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}

In [55]:
result=sess.run(b,feed_dict=dictionary)
print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [56]:
sess.close()

demo code to explain the basic concept of Placeholder

In [57]:
a=tf.placeholder(tf.float32)

In [58]:
b=tf.placeholder(tf.float32)

In [59]:
c=a+b

In [61]:
sess=tf.Session()

In [62]:
result=sess.run(c,feed_dict={a:10,b:20})

In [63]:
print(result)

30.0


In [64]:
d=a*c

In [65]:
result=sess.run(d,feed_dict={a:10,b:20})

In [66]:
print(result)

300.0


In [ ]:
#sess.run(d)

In [67]:
avalues=[1,2,3]
bvalues=[4,5,6]

In [70]:
result=sess.run(c,feed_dict={a:avalues,b:bvalues})
print(result)

[5. 7. 9.]


In [72]:
result=sess.run(d,feed_dict={a:avalues,b:bvalues})