In [1]:
import tensorflow as tf

In [11]:
#using a with 
a=tf.constant(40.0)
u=tf.constant(50.0)
t=tf.placeholder(tf.float32)
s = u*t+(1/2)*a*(t**2)
sess=tf.Session()

In [13]:
result=sess.run(s,feed_dict={t:float(input())})

24.2


In [15]:
print(result)

12922.801


In [16]:
sess.close()

### Regular Multiplication

In [18]:
x=tf.Variable([[1,2,3],[4,5,6]])

In [19]:
y=tf.Variable([[7,8,9],[10,11,12]])

In [20]:
init_op=tf.global_variables_initializer()

In [21]:
sess=tf.Session()

In [22]:
sess.run(init_op)

In [23]:
x

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32_ref>

In [24]:
print(sess.run(x))

[[1 2 3]
 [4 5 6]]


In [25]:
print(sess.run(y))

[[ 7  8  9]
 [10 11 12]]


In [27]:
c1=tf.multiply(x,y)
sess.run(c1)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [28]:
sess.close()

Matrix Multification

In [29]:
x=tf.Variable([[1,2,3],[4,5,6]])

In [30]:
y=tf.Variable([[7,8],[9,10],[11,12]])

In [31]:
init_op=tf.global_variables_initializer()

In [32]:
sess=tf.Session()

In [33]:
sess.run(init_op)

In [34]:
result=tf.matmul(x,y)

In [35]:
print(sess.run(result))

[[ 58  64]
 [139 154]]


In [36]:
x.shape

TensorShape([Dimension(2), Dimension(3)])

In [37]:
y.shape

TensorShape([Dimension(3), Dimension(2)])

In [38]:
sess.close()

Demo for tranning a simple linear regression model in tensorflow. to help understand trainning prossess

In [72]:
# variable 
#first run
w=tf.Variable([.5],tf.float32)
b=tf.Variable([.3],tf.float32)
#second run
#w=tf.Variable([-1.0],tf.float32)
#b=tf.Variable([1.0],tf.float32)

In [73]:
# placeholder
x=tf.placeholder(tf.float32)

In [74]:
#label
y=tf.placeholder(tf.float32)

In [75]:
#linear Model
linear_model=w*x+b

In [76]:
#loss
squared=tf.square(linear_model-y)
loss=tf.reduce_sum(squared)

In [77]:
init=tf.global_variables_initializer()

In [78]:
sess=tf.Session()
sess.run(init)

In [79]:
print(sess.run(loss,feed_dict={x:[1,2,3,4],y:[0,-1,-2,-3]}))

48.46


In [80]:
#loss
squared=tf.square(linear_model-y)
loss=tf.reduce_sum(squared)

In [81]:
#selecting an optimizer
optimizer=tf.train.GradientDescentOptimizer(0.01)

In [82]:
#minimum loss
train=optimizer.minimize(loss)


In [83]:
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)

In [84]:
sess.run(train,{x:[1,2,3,4],y:[0,-1,-2,-3]})

In [85]:
sess.run(b)

array([0.05600001], dtype=float32)

In [86]:
for i in range(1000):
    sess.run(train,{x:[1,2,3,4],y:[0,-1,-2,-3]})

In [87]:
print(sess.run([w,b]))

[array([-0.9999979], dtype=float32), array([0.99999374], dtype=float32)]


In [88]:
sess.run(loss,feed_dict={x:[1,2,3,4],y:[0,-1,-2,-3]})

2.6616931e-11

In [89]:
sess.close()

## Demo of optimizer - solving the Quasratic equation - x*2-10x+25=0

In [90]:
x=tf.Variable(0.0)
#x=tf.Variable(10.0)

In [92]:
cost=x**2-10*x+25
#cost=x**2-2*x+10

In [93]:
#selecting an optimizer
optimizer=tf.train.GradientDescentOptimizer(0.01)

In [95]:
#minimum loss
train=optimizer.minimize(cost)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [97]:
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)

In [98]:
sess.run(train)
print(sess.run(x))

0.099999994


In [99]:
for i in range(1000):
    sess.run(train)

In [100]:
sess.close()

MAX Value

In [114]:
x=tf.Variable([2,50,3,10,4,5,6,7])

In [115]:
y=tf.Variable([[1,2],[3,4],[5,6]])

In [116]:
z=tf.Variable([[1,9],[8,2],[8,7]])

In [117]:
sess=tf.Session()
initop=tf.global_variables_initializer()

In [118]:
sess.run(initop)

In [119]:
sess.run(x)

array([ 2, 50,  3, 10,  4,  5,  6,  7])

In [120]:
x.shape

TensorShape([Dimension(8)])

In [121]:
sess.run(y)

array([[1, 2],
       [3, 4],
       [5, 6]])

Reshape

In [122]:
sess.run(tf.reshape(y,[2,3]))

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
sess.run(z)

array([[1, 9],
       [8, 2],
       [8, 7]])

In [124]:
z.shape

TensorShape([Dimension(3), Dimension(2)])

In [125]:
sess.run(tf.reshape(z,[1,2,3]))

array([[[1, 9, 8],
        [2, 8, 7]]])

Max Value

In [127]:
sess.run(x)

array([ 2, 50,  3, 10,  4,  5,  6,  7])

In [128]:
sess.run(tf.argmax(x,axis=0))

1

In [130]:
sess.run(tf.argmax(z,axis=1))

array([1, 0, 0], dtype=int64)

In [131]:
# Important to Note.....it only gives the location or index of the max value

In [132]:
# this will be used later in neural network classification

In [133]:
sess.close()

## defining the preceptron

In [2]:
import tensorflow as tf
#define place holder for feature and labels
x=tf.placeholder(tf.float32,[None,2]) #2 features
y=tf.placeholder(tf.float32,[None,1]) # labels


In [3]:
# weights and bias
weight=tf.Variable(tf.zeros([2,1]))
bias=tf.Variable(tf.zeros([2,1]))

In [4]:
#input function 
#mull = tf.matmul(x,weight)
#I= tf.add(mult,bias)
I = tf.add(tf.matmul(x,weight),bias)
#activation function
output=tf.sigmoid(I)

In [8]:
# Define the cost /loss fns and the optimizer
individual_loss=tf.nn.sigmoid_cross_entropy_with_logits(labels=y,logits=output)
loss=tf.reduce_mean(individual_loss)
gdo=tf.train.GradientDescentOptimizer(learning_rate=0.01)
train=gdo.minimize(loss)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [9]:
# initilize the variable
init=tf.global_variables_initializer()

In [11]:
sess=tf.Session()
sess.run(init)
#sess.run(train)