## 3x- graph

Demo code for tensorflow graph concept

In [1]:
import tensorflow as tf

In [2]:
graph = tf.get_default_graph()

In [3]:
graph.get_operations()

[]

In [4]:
a = tf.constant(10, name="a")

In [5]:
operations = graph.get_operations()
operations

[<tf.Operation 'a' type=Const>]

In [6]:
b = tf.constant(20, name="b")

In [7]:
operations = graph.get_operations()
operations

[<tf.Operation 'a' type=Const>, <tf.Operation 'b' type=Const>]

In [8]:
#c = a+b
c = tf.add(a, b, name= "c")

In [9]:
operations = graph.get_operations()
operations

[<tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'c' type=Add>]

In [10]:
d = tf.multiply(a,b, name="d")

In [11]:
operations = graph.get_operations()
operations

[<tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'c' type=Add>,
 <tf.Operation 'd' type=Mul>]

In [12]:
e = tf.multiply(c, d, name="e")

In [13]:
operations = graph.get_operations()
operations

[<tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'c' type=Add>,
 <tf.Operation 'd' type=Mul>,
 <tf.Operation 'e' type=Mul>]

In [14]:
sess = tf.Session()

In [15]:
print(sess.run(e))

6000


In [16]:
print(sess.run(d))

200


In [17]:
print(sess.run(c))

30


## 4- Basic Function

Demo code to implement a simple function x^2*Y+Y+C 
x = 3, y= 4, c=2

In [18]:
import tensorflow as tf

In [19]:
x = tf.Variable(3)

In [20]:
y = tf.Variable(4) x = tf.Variable(3), c = tf.constant(2)

In [21]:
c = tf.constant(2)

In [22]:
z = x*x*y + y + c

In [23]:
init_op = tf.global_variables_initializer()

In [24]:
sess = tf.Session()

In [25]:
sess.run(init_op)

In [26]:
print(sess.run(z))

42


### same thing using the user input

In [27]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
c = tf.constant(2.0)

In [28]:
z = x*x*y + y + c

In [29]:
a = float(input())
b = float(input())

4
3


In [30]:
sess = tf.Session()

In [31]:
result = sess.run(z, feed_dict={x:a, y:b})

In [32]:
print(result)

53.0


In [33]:
sess.close()

In [41]:
x=tf.Variable(100.0)
y=tf.constant(20.0)
z=tf.placeholder(tf.float32)

In [46]:
a=x+y
b=z*a
init_op = tf.global_variables_initializer()
sess=tf.Session()
sess.run(init_op)
result=sess.run(b,feed_dict={z:float(input())})

25.0


In [47]:
print(result)

3000.0


In [48]:
sess.close()

In [49]:
# create A matrix and find the possition of max value
y=tf.Variable([[150,250,750],[500,600,800],[900,200,540],[990,220,330]])
init_op = tf.global_variables_initializer()
sess=tf.Session()
sess.run(init_op)


In [50]:
sess.run(tf.argmax(y,axis=0))

array([3, 1, 1], dtype=int64)

In [51]:
sess.run(tf.argmax(y,axis=1))

array([2, 2, 0, 0], dtype=int64)

In [52]:
result=sess.run(tf.reshape(y,[1,3,4]))

In [53]:
result

array([[[150, 250, 750, 500],
        [600, 800, 900, 200],
        [540, 990, 220, 330]]])

In [54]:
sess.run(y)

array([[150, 250, 750],
       [500, 600, 800],
       [900, 200, 540],
       [990, 220, 330]])

In [56]:
result=sess.run(tf.reshape(y,[1,4,3]))
result

array([[[150, 250, 750],
        [500, 600, 800],
        [900, 200, 540],
        [990, 220, 330]]])

Perform Matrix Multiplication

In [58]:
x=tf.Variable([1,2,3])
y=tf.Variable([3,4,5])

In [59]:
init_op = tf.global_variables_initializer()
sess=tf.Session()
sess.run(init_op)

In [61]:
result=tf.matmul(x,y)

ValueError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [3], [3].

In [62]:
x=tf.Variable([[1,2,3],[4,5,6]])
y=tf.Variable([[7],[8],[9]])

In [63]:
init_op = tf.global_variables_initializer()
sess=tf.Session()
sess.run(init_op)

In [66]:
result=sess.run(tf.matmul(x,y))

In [67]:
result

array([[ 50],
       [122]])

In [68]:
sess.close()

In [69]:
a=tf.Variable([[150,250,750],[500,600,800],[900,200,540],[990,220,330]])
b=tf.Variable([[390],[890],[790]])

In [70]:
init_op = tf.global_variables_initializer()
sess=tf.Session()
sess.run(init_op)

In [72]:
result=sess.run(tf.matmul(a,b))
result

array([[ 873500],
       [1361000],
       [ 955600],
       [ 842600]])

In [74]:
result=sess.run(tf.matmul(b,a))
result

ValueError: Dimensions must be equal, but are 1 and 4 for 'MatMul_6' (op: 'MatMul') with input shapes: [3,1], [4,3].

In [75]:
sess.close()

In [76]:
A=tf.Variable([[1,2,3],[4,5,6],[7,8,9]])
B=tf.Variable([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [77]:
sess=tf.Session()
initop=tf.global_variables_initializer()
sess.run(initop)

In [79]:
sess.run(tf.reshape(A,[1,3,3]))

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [80]:
sess.run(tf.reshape(B,[1,4,3]))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [81]:
sess.close()

In [82]:
X=tf.Variable([[1,2,3],[4,5,6],[7,8,9]])
Y=tf.Variable([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [83]:
sess=tf.Session()
initop=tf.global_variables_initializer()
sess.run(initop)

In [85]:
sess.run(tf.argmax(A,0))

array([2, 2, 2], dtype=int64)

In [86]:
sess.run(tf.argmax(B,1))

array([3, 3, 3], dtype=int64)

In [87]:
sess.close()

In [4]:
#y = tf.Variable(5) 
#x = tf.Variable(10)
#c = tf.constant(20)

x=tf.placeholder(tf.float32)
Y=x**2-20*x+100
sess=tf.Session()

In [5]:
result=sess.run(Y,feed_dict={x:float(input())})
result

20.0


100.0